# Generated by Django 3.2.8 on 2021-10-16 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authGestifyApp', '0002_alter_producto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authGestifyApp.user'),
            preserve_default=False,
        ),
    ]
