# Generated by Django 3.2.7 on 2021-10-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authGestifyApp', '0003_proveedor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Username'),
        ),
    ]
